CREATE TABLE LOCATION(
	Location_ID INT NOT NULL,
	Street_address VARCHAR(30) NOT NULL,
	City VARCHAR(20) NOT NULL,
	State CHAR(2) NOT NULL,
	Zip_code CHAR(5) NOT NULL,
	PRIMARY KEY(Location_ID));
	
CREATE TABLE TRIP(
	Trip_ID INT NOT NULL,
	Start_date DATE NOT NULL,
	Start_time TIME(0) NOT NULL,
	End_date DATE,
	End_time TIME(0),
	Mileage DECIMAL(6, 2) NOT NULL,
	PRIMARY KEY(Trip_ID));
	
CREATE TABLE START_LOCATION(
	Location_ID INT NOT NULL,
	Trip_ID INT NOT NULL,
	PRIMARY KEY(Location_ID, Trip_ID),
	FOREIGN KEY(Location_ID) REFERENCES LOCATION(Location_ID),
	FOREIGN KEY(Trip_ID) REFERENCES TRIP(Trip_ID));
	
CREATE TABLE END_LOCATION(
	Location_ID INT NOT NULL,
	Trip_ID INT NOT NULL,
	PRIMARY KEY(Location_ID, Trip_ID),
	FOREIGN KEY(Location_ID) REFERENCES LOCATION(Location_ID),
	FOREIGN KEY(Trip_ID) REFERENCES TRIP(Trip_ID));